# ./docker-compose.yml

version: '3'

services:
  database:
    build: ./db
    image: harsha9199/db:latest
    ports:
      - "3306:3306"
  redis:
    build: ./redis
    image: harsha9199/redis:latest
    ports:
        - 6379:6379
  web:
    build: .
    image: harsha9199/ipl:latest
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true